{{ if and .Values.zabbixServer.enabled .Values.zabbixServer.zabbixServerHA.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "zabbix.fullname" . }}-ha-helper
  labels:
    app: {{ template "zabbix.fullname" . }}-ha-helper
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
  {{- if .Values.zabbixServer.zabbixServerHA.roleBinding.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.zabbixServerHA.roleBinding.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "zabbix.serviceAccountName" . }}
- kind: ServiceAccount
  name: {{ template "zabbix.fullname" . }}-ha-helper
roleRef:
  kind: Role
  name: {{ template "zabbix.fullname" . }}-ha-helper
  apiGroup: rbac.authorization.k8s.io
{{ end }}
