{{ if and .Values.zabbixServer.enabled .Values.zabbixServer.zabbixServerHA.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zabbix.fullname" . }}-ha-helper
  labels:
    app: {{ template "zabbix.fullname" . }}-ha-helper
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: {{ include "zabbix.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-zabbix-server
    app.kubernetes.io/managed-by: {{ .Release.Service }}-zabbix-server
  {{- if .Values.zabbixServer.zabbixServerHA.serviceAccount.annotations }}
  annotations:
    {{- range $key,$value := .Values.zabbixServer.zabbixServerHA.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{ end }}
