name: Helm Chart Tests, internal DB, no HA, create Secret

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main

jobs:
  test_helm_installation:
    if: github.event.repository.fork == true || github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kind
        uses: helm/kind-action@v1

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh

      - name: Create Namespace in Kind
        run: |
          kubectl create namespace zabbix

      - name: Run Helm install with default values (AppVersion)
        run: |
          helm install --wait --namespace zabbix zabbix ./charts/zabbix

      - name: Run helm test CURRENT LTS
        run: |
          kubectl get pods -o wide --namespace zabbix
          helm test --namespace zabbix zabbix

      - name: Run helm uninstall
        run: |
          helm uninstall --wait zabbix --namespace zabbix
          kubectl delete secrets --all --namespace zabbix

      - name: Run Helm install with version 6.0 LTS
        run: |
          helm install --wait --namespace zabbix zabbix --set zabbixImageTag=ubuntu-6.0-latest ./charts/zabbix

      - name: Run helm test 6.0
        run: |
          kubectl get pods -o wide --namespace zabbix
          helm test --namespace zabbix zabbix

      - name: Run Helm upgrade with default values (AppVersion)
        run: |
          helm upgrade --wait --namespace zabbix zabbix ./charts/zabbix

      - name: Run helm test CURRENT LTS
        run: |
          kubectl get pods -o wide --namespace zabbix
          helm test --namespace zabbix zabbix

      - name: Run Helm upgrade with version 7.2 non-LTS
        run: |
          helm upgrade --wait --namespace zabbix zabbix --set zabbixImageTag=ubuntu-7.2-latest ./charts/zabbix

      - name: Run helm test 7.2 non-LTS
        run: |
          kubectl get pods -o wide --namespace zabbix
          helm test --namespace zabbix zabbix
