---
name: Linters

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main

jobs:
  codespell:
    if: github.event.repository.fork == true || github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run code spelling check
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: aks,NotIn
